greeting:
  message: "hello"

quarkus:
  datasource:
    db-kind: mssql
    username: admin
    password: quarkus_test
    jdbc:
      url: jdbc:sqlserver://localhost/quarkus_test

  hibernate-orm:
    database:
      generation: none
    log:
      sql: true
    sql-load-script: no-file

job:
  schedule:
    time: "*/1 * * * * ?"